// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwboxveqgskdshglfaqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3Ym94dmVxZ3NrZHNoZ2xmYXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MjAyMTUsImV4cCI6MjA3NDQ5NjIxNX0.P8UGYiOAgfT9emaW1oemqD8k7KTzeWOatVWnL6aIPhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});